/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package finalbanco;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author agust
 */
public class Cliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreC = new javax.swing.JTextField();
        apellidoC = new javax.swing.JTextField();
        fechaC = new javax.swing.JTextField();
        cuitC = new javax.swing.JTextField();
        domiC = new javax.swing.JTextField();
        locC = new javax.swing.JTextField();
        mailC = new javax.swing.JTextField();
        hijC = new javax.swing.JTextField();
        provC = new javax.swing.JComboBox<>();
        estadoC = new javax.swing.JComboBox<>();
        genC = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        salirC = new javax.swing.JButton();
        limpiarC = new javax.swing.JButton();
        CREAR = new javax.swing.JButton();
        validacionC = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Cliente");
        setPreferredSize(new java.awt.Dimension(750, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreC.setPreferredSize(new java.awt.Dimension(250, 22));
        nombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCActionPerformed(evt);
            }
        });
        getContentPane().add(nombreC, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        apellidoC.setPreferredSize(new java.awt.Dimension(250, 22));
        getContentPane().add(apellidoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        fechaC.setPreferredSize(new java.awt.Dimension(250, 22));
        getContentPane().add(fechaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        cuitC.setPreferredSize(new java.awt.Dimension(250, 22));
        cuitC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cuitCKeyTyped(evt);
            }
        });
        getContentPane().add(cuitC, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        domiC.setPreferredSize(new java.awt.Dimension(250, 22));
        getContentPane().add(domiC, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        locC.setPreferredSize(new java.awt.Dimension(250, 22));
        getContentPane().add(locC, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        mailC.setPreferredSize(new java.awt.Dimension(250, 22));
        mailC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mailCKeyTyped(evt);
            }
        });
        getContentPane().add(mailC, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, -1, -1));

        hijC.setPreferredSize(new java.awt.Dimension(250, 22));
        hijC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hijCKeyTyped(evt);
            }
        });
        getContentPane().add(hijC, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

        provC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buenos Aires", "CABA", "Catamarca", "Chaco", "Chubut", "Córdoba", "Corrientes", "Entre Ríos", "Formosa", "Jujuy", "La Pampa", "La Rioja" }));
        getContentPane().add(provC, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 250, -1));

        estadoC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero/a", "Casado/a", "Divorciado/a", "Viudo/a" }));
        getContentPane().add(estadoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 250, -1));

        genC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Otro" }));
        getContentPane().add(genC, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 250, -1));

        jLabel1.setText("NOMBRE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabel2.setText("APELLIDO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel3.setText("FECHA DE NACIMIENTO (dd/mm/aa)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel4.setText("GÉNERO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel5.setText("DOMICILIO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel6.setText("LOCALIDAD");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        jLabel7.setText("PROVINCIA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        jLabel8.setText("E-MAIL");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));

        jLabel9.setText("ESTADO CIVIL");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jLabel10.setText("HIJOS");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));

        jLabel11.setText("CUIT/CUIL");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        salirC.setText("SALIR");
        salirC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirCActionPerformed(evt);
            }
        });
        getContentPane().add(salirC, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 150, 31));

        limpiarC.setText("LIMPIAR");
        limpiarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarCActionPerformed(evt);
            }
        });
        getContentPane().add(limpiarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, 150, 31));

        CREAR.setText("CREAR");
        CREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREARActionPerformed(evt);
            }
        });
        getContentPane().add(CREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 150, 31));

        validacionC.setForeground(new java.awt.Color(255, 0, 51));
        validacionC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(validacionC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 530, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCActionPerformed

    private void salirCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirCActionPerformed
       
        
        dispose (); 
        
        
    }//GEN-LAST:event_salirCActionPerformed

    private void limpiarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarCActionPerformed
       
        
            nombreC.setText("");
            apellidoC.setText("");
            cuitC.setText("");
            domiC.setText("");
            fechaC.setText("");
            hijC.setText("");         
            mailC.setText("");
            locC.setText("");
            
            genC.setSelectedIndex(0);
            provC.setSelectedIndex(0);
            estadoC.setSelectedIndex(0);    
                      
          
      
             
        
        
        
    }//GEN-LAST:event_limpiarCActionPerformed

    private void CREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREARActionPerformed
       
                 //Generador de txt 
                
                 String nombreT = nombreC.getText (); 
                 String apellidoT = apellidoC.getText (); 
                 String cuitT = cuitC.getText(); 
                 String domiT = domiC.getText(); 
                 String fechaNacT = fechaC.getText(); 
                 String hijT = hijC.getText (); 
                 String mailT = mailC.getText(); 
                 String locT = locC.getText(); 
                 String genT = genC.getSelectedItem().toString();
                 String provT = provC.getSelectedItem().toString();
                 String estadoT = estadoC.getSelectedItem().toString();
                 
                 
                 
                 try

                {



                FileWriter archivoCliente = new FileWriter ( "ArchivoCliente.txt", true); 
 
                archivoCliente.write ( "\t \n Nombre: " + nombreT + 
                                        " Apellido: " + apellidoT + 
                                        " Fecha de nacimiento: " +  fechaNacT + 
                                        " Género " + genT +
                                        " Cuit: "+ cuitT + 
                                        " Domicilio: " + domiT + 
                                        " Localidad: " + locT +
                                        " Provincia " + provT + 
                                        " Estado Civil " + estadoT +
                                        " Hijos: " +  hijT +
                                        " Mail: " + mailT   ) ;     
                                       
                  

                JOptionPane.showMessageDialog( null , "El archivo fue creado con éxito", "Mensaje", JOptionPane.INFORMATION_MESSAGE);


                archivoCliente.close();





                }

                catch ( Exception e )

                {


                 JOptionPane.showInternalMessageDialog( null , "Error");



                } 


        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_CREARActionPerformed

    private void hijCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hijCKeyTyped
       
        
        
        if ( hijC.getText().matches ("[0-9]*") )
            {validacionC.setText( "" ) ; }
        
               
        
        else { validacionC.setText( "Ingrese un número" );                              
                hijC.setText("")  ; } 
        
        
        
        
        
    }//GEN-LAST:event_hijCKeyTyped

    private void cuitCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cuitCKeyTyped
     
        
             
        if ( cuitC.getText().matches ("[0-9]*") )
            {validacionC.setText( "" ) ; }
        
               
        
        else { validacionC.setText( "Ingrese un número" );
                cuitC.setText("")  ; } 
        
        
        
        
    }//GEN-LAST:event_cuitCKeyTyped

    private void mailCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailCKeyTyped
       
        
        
        if ( mailC.getText().contains ( "@" )  ) { validacionC.setText( "");  }
        
        else { validacionC.setText( " Inrgese mail válido ");  }
        
        
        if ( mailC.getText().contains ( "." ) ) { validacionC.setText( "") ;  }
        
        else { validacionC.setText( " Inrgese mail válido ");  }
        
        
        
        
        
    }//GEN-LAST:event_mailCKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CREAR;
    private javax.swing.JTextField apellidoC;
    private javax.swing.JTextField cuitC;
    private javax.swing.JTextField domiC;
    private javax.swing.JComboBox<String> estadoC;
    private javax.swing.JTextField fechaC;
    private javax.swing.JComboBox<String> genC;
    private javax.swing.JTextField hijC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton limpiarC;
    private javax.swing.JTextField locC;
    private javax.swing.JTextField mailC;
    private javax.swing.JTextField nombreC;
    private javax.swing.JComboBox<String> provC;
    private javax.swing.JButton salirC;
    private javax.swing.JLabel validacionC;
    // End of variables declaration//GEN-END:variables
}
