/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalbanco;

/**
 *
 * @author agust
 */
public class Ingreso extends javax.swing.JFrame {

   
    
    
    
    
    
    public Ingreso() {
        initComponents();
     
         this.setLocationRelativeTo(null);
         this.setTitle ("Inicio"); 
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelIng = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cliente = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        seguros = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        cambioMoneda = new javax.swing.JMenu();
        info = new javax.swing.JMenu();
        salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));
        setType(java.awt.Window.Type.UTILITY);

        javax.swing.GroupLayout PanelIngLayout = new javax.swing.GroupLayout(PanelIng);
        PanelIng.setLayout(PanelIngLayout);
        PanelIngLayout.setHorizontalGroup(
            PanelIngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );
        PanelIngLayout.setVerticalGroup(
            PanelIngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );

        cliente.setText("Cliente");
        cliente.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                clienteMenuSelected(evt);
            }
        });
        cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteMouseClicked(evt);
            }
        });
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        jMenuBar1.add(cliente);

        jMenu2.setText("Producto");

        seguros.setText("Seguros");
        seguros.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
                segurosMenuKeyTyped(evt);
            }
        });
        seguros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segurosActionPerformed(evt);
            }
        });
        jMenu2.add(seguros);

        jMenuItem2.setText("Tasa de interés");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        cambioMoneda.setText("Cambio de moneda");
        cambioMoneda.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                cambioMonedaMenuSelected(evt);
            }
        });
        jMenuBar1.add(cambioMoneda);

        info.setText("Información");
        jMenuBar1.add(info);

        salir.setText("Salir");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenuBar1.add(salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelIng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelIng, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void segurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segurosActionPerformed
     
        
        Seguros1 F1 = new Seguros1(); 
        F1.setLocationRelativeTo (null); 
        F1.setVisible (true); 
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_segurosActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
       
     
        
        
        
    }//GEN-LAST:event_salirActionPerformed

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        dispose();
        
        
    }//GEN-LAST:event_salirMouseClicked

    private void clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteMouseClicked
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_clienteMouseClicked

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        
      
  
        
        
        
        
        
        
        
    }//GEN-LAST:event_clienteActionPerformed

    private void clienteMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_clienteMenuSelected
      
        
          
        Cliente internal1 = new Cliente (); 
        PanelIng.add (internal1);        
        internal1.show(); 
        this.setLocationRelativeTo(null);
        this.setTitle ("Inicio"); 
        
        
    }//GEN-LAST:event_clienteMenuSelected

    private void segurosMenuKeyTyped(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_segurosMenuKeyTyped
       
     
        
        
    }//GEN-LAST:event_segurosMenuKeyTyped

    private void cambioMonedaMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_cambioMonedaMenuSelected
      
        
        
            
        CambioMoneda internal2 = new CambioMoneda (); 
        PanelIng.add (internal2);        
        internal2.show(); 
        this.setLocationRelativeTo(null);
        this.setTitle ("Cambio de Moneda"); 
        
        
        
        
        
        
    }//GEN-LAST:event_cambioMonedaMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelIng;
    private javax.swing.JMenu cambioMoneda;
    private javax.swing.JMenu cliente;
    private javax.swing.JMenu info;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu salir;
    private javax.swing.JMenuItem seguros;
    // End of variables declaration//GEN-END:variables
}
