/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalbanco;

import java.io.FileWriter;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Seguros1 extends javax.swing.JFrame {

    /**
     * Creates new form Seguros
     */
    public Seguros1() {
        initComponents();
        comboFranquicia.setEnabled ( false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        Benef31 = new javax.swing.JTextField();
        itemV = new javax.swing.JComboBox<>();
        Benef38 = new javax.swing.JTextField();
        item2V = new javax.swing.JComboBox<>();
        Benef40 = new javax.swing.JTextField();
        item3V = new javax.swing.JComboBox<>();
        Benef42 = new javax.swing.JTextField();
        item4V = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        muerteV = new javax.swing.JCheckBox();
        muerteVA = new javax.swing.JCheckBox();
        internacionV = new javax.swing.JCheckBox();
        paralisisV = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        diasV = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        domTxt = new javax.swing.JTextField();
        comboMarca = new javax.swing.JComboBox<>();
        modelImp = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TercComp = new javax.swing.JCheckBox();
        RespCiv = new javax.swing.JCheckBox();
        TrSinFran = new javax.swing.JCheckBox();
        TrConFran = new javax.swing.JCheckBox();
        granizoCheck = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        comboFranquicia = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        anImp = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        incendioC = new javax.swing.JCheckBox();
        roboC = new javax.swing.JCheckBox();
        inundacionC = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        hel = new javax.swing.JCheckBox();
        lav = new javax.swing.JCheckBox();
        tel = new javax.swing.JCheckBox();
        net = new javax.swing.JCheckBox();
        games = new javax.swing.JCheckBox();
        cocina = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        TipCobertura = new javax.swing.JComboBox<>();
        cuilImp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nomImp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        telImp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mailImp = new javax.swing.JTextField();
        ContratarHogar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seguros ");
        setType(java.awt.Window.Type.UTILITY);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 43, -1, -1));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, -1, -1));

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Beneficiario"));
        jPanel18.setName("Beneficiario"); // NOI18N

        itemV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Item 1", "Item 2", "Item 3", "Item 4" }));

        item2V.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Item 1", "Item 2", "Item 3", "Item 4" }));

        item3V.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Item 1", "Item 2", "Item 3", "Item 4" }));

        item4V.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(Benef31, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(itemV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(Benef38, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(item2V, 0, 80, Short.MAX_VALUE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(Benef40, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(item3V, 0, 80, Short.MAX_VALUE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(Benef42, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(item4V, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Benef31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Benef38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item2V, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Benef40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item3V, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Benef42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item4V, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Coberturas"));

        muerteV.setText("Muerte");
        muerteV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muerteVActionPerformed(evt);
            }
        });

        muerteVA.setText("Muerte Accidental");

        internacionV.setText("Días de internación");

        paralisisV.setText("Paralisis parcial o Total");

        jLabel13.setText("Días");

        diasV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30", "60", "90" }));
        diasV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diasVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(internacionV)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(diasV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(muerteV)
                            .addComponent(muerteVA)
                            .addComponent(paralisisV))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(muerteV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(muerteVA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(internacionV)
                    .addComponent(jLabel13)
                    .addComponent(diasV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paralisisV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jTabbedPane1.addTab("Seguros Vida", jPanel3);

        jPanel1.setMinimumSize(new java.awt.Dimension(700, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 400));

        jLabel5.setText("Dominio ");

        domTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domTxtActionPerformed(evt);
            }
        });

        comboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "FORD", "FIAT", "AUDI" }));
        comboMarca.setToolTipText("");

        modelImp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Punto", "500", "Palio", "Fiesta", "Focus", "Ecosport", "A3", "A4", "A5" }));
        modelImp.setToolTipText("");

        jLabel6.setText("Marca");

        jLabel7.setText("Modelo");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Coberturas"));

        TercComp.setText("Terceros Completo");
        TercComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TercCompActionPerformed(evt);
            }
        });

        RespCiv.setText("Responsabilidad Civil");
        RespCiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespCivActionPerformed(evt);
            }
        });

        TrSinFran.setText("Todo Riesgo sin Franquicia");
        TrSinFran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrSinFranActionPerformed(evt);
            }
        });

        TrConFran.setText("Todo Riesgo con Franquicia");
        TrConFran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrConFranActionPerformed(evt);
            }
        });

        granizoCheck.setText("Granizo");
        granizoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                granizoCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TrConFran)
                        .addComponent(TercComp, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RespCiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TrSinFran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(granizoCheck))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TercComp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RespCiv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TrSinFran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TrConFran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(granizoCheck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("Franquicia");

        comboFranquicia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "20000", "40000", "60000", "80000" }));
        comboFranquicia.setToolTipText("");

        jLabel9.setText("Premio: ");

        jLabel10.setText("Prima por mes:");

        jLabel11.setText("Año");

        anImp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anImpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(29, 29, 29)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(domTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(comboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addComponent(modelImp, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(comboFranquicia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(anImp, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(domTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modelImp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(comboFranquicia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 226, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(anImp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Seguros Vehiculo", jPanel1);

        jPanel4.setPreferredSize(new java.awt.Dimension(701, 300));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Coberturas"));

        incendioC.setText("Incendio");
        incendioC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incendioCActionPerformed(evt);
            }
        });

        roboC.setText("Robo ");
        roboC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roboCActionPerformed(evt);
            }
        });

        inundacionC.setText("Inundación");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(incendioC)
                    .addComponent(roboC)
                    .addComponent(inundacionC))
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(incendioC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roboC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inundacionC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Elementos Dañados/Robados"));

        hel.setText("Heladera");
        hel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helActionPerformed(evt);
            }
        });

        lav.setText("Lavaropas");
        lav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lavActionPerformed(evt);
            }
        });

        tel.setText("Televisor");

        net.setText("Notebook");
        net.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netActionPerformed(evt);
            }
        });

        games.setText("Consola Games");

        cocina.setText("Cocina");
        cocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hel)
                    .addComponent(lav)
                    .addComponent(tel))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cocina)
                    .addComponent(games)
                    .addComponent(net))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hel)
                    .addComponent(net))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lav)
                    .addComponent(games))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tel)
                    .addComponent(cocina))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de cobertura"));

        TipCobertura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Parcial", "Media", "Total" }));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(TipCobertura, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(TipCobertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Seguros Hogar", jPanel4);

        jLabel1.setText("CUIL/CUIT");

        jLabel2.setText("Nombre y Apellido");

        jLabel3.setText("Telefono ");

        telImp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telImpActionPerformed(evt);
            }
        });

        jLabel4.setText("Email");

        ContratarHogar.setText("Contratar");
        ContratarHogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContratarHogarActionPerformed(evt);
            }
        });

        jLabel12.setText("Seleccione primero todos los seguros y luego presione contratar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cuilImp, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mailImp, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(telImp)
                            .addComponent(nomImp))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContratarHogar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cuilImp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomImp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telImp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(mailImp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(ContratarHogar))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telImpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telImpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telImpActionPerformed

    private void domTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domTxtActionPerformed

    private void RespCivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespCivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RespCivActionPerformed

    private void TrConFranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrConFranActionPerformed
        
        
       
        RespCiv.setSelected (false) ; 
        
        if ( TrConFran.isSelected ()== true)  { 
        
        RespCiv.setSelected (true) ; 
        comboFranquicia.setEnabled (true); 
           
        
        
    }//GEN-LAST:event_TrConFranActionPerformed

        else   {  comboFranquicia.setEnabled (false); } 
        
    }    
    
    private void granizoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_granizoCheckActionPerformed
        
        RespCiv.setSelected (false) ; 
        TrConFran.setSelected (false) ;
        TrSinFran.setSelected (false) ;
        
        
        if ( granizoCheck.isSelected ()== true)  { 
        
        RespCiv.setSelected (true) ; 
        TrConFran.setSelected (true) ;
        TrSinFran.setSelected (true) ;
        
        
   }     
        
    }//GEN-LAST:event_granizoCheckActionPerformed

    private void anImpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anImpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anImpActionPerformed

    private void TrSinFranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrSinFranActionPerformed
        
        
        
        RespCiv.setSelected (false) ; 
        
        if ( TrSinFran.isSelected ()== true)  { 
        
        RespCiv.setSelected (true) ; 
        
        
    }//GEN-LAST:event_TrSinFranActionPerformed
    }  
    private void incendioCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incendioCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incendioCActionPerformed

    private void roboCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roboCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roboCActionPerformed

    private void helActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helActionPerformed

    private void lavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lavActionPerformed

    private void netActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netActionPerformed

    private void cocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cocinaActionPerformed

    private void TercCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TercCompActionPerformed
        RespCiv.setSelected (false) ; 
        
        if ( TercComp.isSelected ()== true)  { 
        
        RespCiv.setSelected (true) ; 
        
        
        }   
    }//GEN-LAST:event_TercCompActionPerformed

    private void ContratarHogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContratarHogarActionPerformed
        
          
        
             //Generador de txt 
                
            
                
                //JCheckBox[] checkBoxesCobert = {TercComp, RespCiv, TrSinFran, TrConFran, granizoCheck}; 
                
           
               
                
                //datos 1
                
                 
                 String cuilTxt = cuilImp.getText (); 
                 String nombreTxt = nomImp.getText (); 
                 String telTxt = telImp.getText(); 
                 String mailTxt = mailImp.getText(); 
                 
                 
                 String SegV = "\nSEGURO VEHÍCULO \n";
                 String dominioTxt = domTxt.getText(); 
                 String marcaTxt = comboMarca.getSelectedItem().toString() ;  
                 String modeloTxt = modelImp.getSelectedItem().toString() ; 
                 String franqTxt =  comboFranquicia.getSelectedItem().toString() ; 
                 String anTxt = anImp.getText ();
                 
                 
                 //checkbox COBERTURAS VEHICULO 
                 
                  /* PRUEBA 1 
                 
                 String cobTxt1 = TercComp.getText () ;
                 String cobTxt2 = RespCiv.getText () ; 
                 String cobTxt3 = TrSinFran.getText () ; 
                 String cobTxt4 = TrConFran.getText () ; 
                 String cobTxt5 = granizoCheck.getText () ; */
                  
                 
                 String cobTxt1 = "" ;
                 String cobTxt2 = "" ; 
                 String cobTxt3 = "" ; 
                 String cobTxt4 = "" ; 
                 String cobTxt5 = "" ; 
                  
                 
              
                 JCheckBox [] SelCheck1_C = {TercComp, RespCiv, TrSinFran, TrConFran, granizoCheck};                    
                 for( JCheckBox x: SelCheck1_C ) { 
                                 
                       
                      if ( TercComp.isSelected() )    { cobTxt1= incendioC.getText(); };
                      if ( RespCiv.isSelected() )        { cobTxt2 = roboC.getText(); };           
                      if ( TrSinFran.isSelected() )  { cobTxt3 = inundacionC.getText(); };           
                      if ( TrConFran.isSelected() )  { cobTxt4 = inundacionC.getText(); };   
                      if ( granizoCheck.isSelected() )  { cobTxt5 = inundacionC.getText(); };    
                    }
                  
                 
                 
                
                 
                 //datos2 HOGAR 
        
                    
                 
                 //COBERTURA checkbox HOGAR 
        
                 /* PRUEBA 1 
                  
                 String incendioTxt = incendioC.getText(); 
                 String roboTxt = roboC.getText() ;  
                 String inundacionTxt = inundacionC.getText() ;  */  
                 
                 
                  String SegH = "\nSEGURO HOGAR \n";
                  
                  String incendioTxt="";
                  String roboTxt ="";
                  String inundacionTxt="";
                 
                  
                  
                 JCheckBox [] SelCheck1_A = {incendioC, roboC, inundacionC } ;                    
                 for( JCheckBox x: SelCheck1_A ) { 
                                 
                       
                      if ( incendioC.isSelected() )    { incendioTxt = incendioC.getText(); };
                      if ( roboC.isSelected() )        {  roboTxt  = roboC.getText(); };           
                      if ( inundacionC.isSelected() )  { inundacionTxt = inundacionC.getText(); };           
                     
                       
                    }
                  
                
          
                 //elementos dañados robados checkbox
                 
                 /* PRUEBA 1 
                 
                 String cobTxt1_1 = hel.getText();  
                 String cobTxt1_2 = lav.getText() ;  
                 String cobTxt1_3 = tel.getText() ;  
                 String cobTxt1_4 = net.getText(); 
                 String cobTxt1_5 = games.getText() ;  
                 String cobTxt1_6 = cocina.getText() ;  */  
                 
                 
                  String cobTxt1_1="";
                  String cobTxt1_2="";
                  String cobTxt1_3="";
                  String cobTxt1_4="";
                  String cobTxt1_5="";
                  String cobTxt1_6="";
               
                  
                 JCheckBox [] SelCheck1_B = {hel, lav, tel, net , games , cocina } ;
                 //String [] SelCheck2 = {} ;
                 
                 for( JCheckBox x: SelCheck1_B ) { 
                                 
                       
                      if ( hel.isSelected() )    { cobTxt1_1 = hel.getText(); };
                      if ( lav.isSelected() )    { cobTxt1_2 = lav.getText(); };           
                      if ( tel.isSelected() )    { cobTxt1_3 = tel.getText(); };           
                      if ( net.isSelected() )    { cobTxt1_4 = net.getText(); };          
                      if ( games.isSelected() )  { cobTxt1_5 = games.getText(); };
                      if ( cocina.isSelected() ) { cobTxt1_6 = cocina.getText(); };
                     
                       
                    }

                 
                 
                
                 //tipo de cobertura 
                 
                String TipcoberturaTxt =  TipCobertura.getSelectedItem().toString() ; 
                 
               
                
                 //datos3 SEG VIDA 
                
                  String SegVida = "\nSEGURO VIDA \n";
                 
                 //checkbox 
                 
                  String cobTxt2_1="";
                  String cobTxt2_2="";
                  String cobTxt2_3="";
                  String cobTxt2_4="";
                  String cobTxt2_5="";
                  String cobTxt2_6="";
               
                  
                 JCheckBox [] SelCheck1_D = { muerteV, muerteVA, internacionV, paralisisV  } ;
                 //String [] SelCheck2 = {} ;
                 
                 for( JCheckBox x: SelCheck1_D ) { 
                                 
                       
                      if ( muerteV.isSelected() )    { cobTxt2_1 = muerteV.getText(); };
                      if ( muerteVA.isSelected() )    { cobTxt2_2 = muerteVA.getText(); };           
                      if ( internacionV.isSelected() )    { cobTxt2_3 = internacionV.getText(); };           
                      if ( paralisisV.isSelected() )    { cobTxt2_4 = paralisisV.getText(); };          
                     
                     
                       
                    }

                
                 
                 //combobox 
                             
                 String diasTxt =  diasV.getSelectedItem().toString() ;  
                 String itemTxt1 = itemV.getSelectedItem().toString() ;  
                 String itemTxt2 = item2V.getSelectedItem().toString() ; 
                 String itemTxt3 = item3V.getSelectedItem().toString() ; 
                 String itemTxt4 = item4V.getSelectedItem().toString() ; 
                
               
                
                
                
                 try

                {



                FileWriter archivoContratar = new FileWriter ( "ArchivoContratar.txt", true); 
 
                archivoContratar.write ( 
                                        "\t\nCUIL/CUIT: " + cuilTxt + 
                                        "\nNombre y Apellido: " + nombreTxt + 
                                        "\nTeléfono: "+ telTxt + 
                                        "\nE-Mail: " + mailTxt + 
                                         
                                                
                                                
                                                
                                                
                                                
                                        //SEGURO VEHICULO        
                                        "\t \n" + SegV +   
                                                
                                        "\nDominio: " +  dominioTxt +
                                        "\nMarca: " +  marcaTxt +
                                        "\nModelo: " + modeloTxt + 
                                        "\nFranquicia: " + franqTxt + 
                                        "\nCoberturas: " + "\n"+ cobTxt1 + "\n"+ cobTxt2 + "\n"+ cobTxt3 + "\n"+ cobTxt4 + "\n"+ cobTxt5 + "\n" +
                                        "\nAño: " + anTxt +
                
                                        //SEGURO HOGAR          
                                        "\t \n" + SegH + 
                                       
                                        "\nCoberturas: " + "\n"+ incendioTxt + "\n"+ roboTxt+ "\n"+ inundacionTxt + 
                                        "\nElementos dañados/robados : " +  "\n"+ cobTxt1_1 + "\n"+ cobTxt1_2 + "\n"+ cobTxt1_3 + "\n"+ cobTxt1_4 + "\n"+ cobTxt1_5+ "\n"+ cobTxt1_6  + 
                                        "\nTipo de cobertura : " + TipcoberturaTxt  +
                                        
                                         
                                        //SEGURO VIDA     
                                        "\t \n" + SegVida + 
                                        "\nCoberturas: " + "\n"+  cobTxt2_1 + "\n" +  cobTxt2_2 + cobTxt2_3 + " Días:  " +  diasTxt  + "\n" + cobTxt2_4 + 
                                        "\nBeneficiario " + "\n"+ itemTxt1 + "\n" + itemTxt2 + "\n"+ itemTxt3 + "\n"+ itemTxt4 
                                         
                                             );     
                                          
                                            
                                                   
               
                      
/**/
                JOptionPane.showMessageDialog( null , "El archivo fue creado con éxito", "Mensaje", JOptionPane.INFORMATION_MESSAGE);


               archivoContratar.close();





                }

                catch ( Exception e )

                {


                 JOptionPane.showInternalMessageDialog( null , "Error");



                } 

        
        
        
        
    }//GEN-LAST:event_ContratarHogarActionPerformed

    private void muerteVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muerteVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_muerteVActionPerformed

    private void diasVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diasVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diasVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seguros1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seguros1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seguros1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seguros1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seguros1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Benef1;
    private javax.swing.JTextField Benef10;
    private javax.swing.JComboBox<String> Benef11;
    private javax.swing.JComboBox<String> Benef12;
    private javax.swing.JComboBox<String> Benef13;
    private javax.swing.JTextField Benef14;
    private javax.swing.JTextField Benef15;
    private javax.swing.JTextField Benef16;
    private javax.swing.JComboBox<String> Benef17;
    private javax.swing.JTextField Benef18;
    private javax.swing.JTextField Benef19;
    private javax.swing.JTextField Benef2;
    private javax.swing.JTextField Benef20;
    private javax.swing.JTextField Benef21;
    private javax.swing.JComboBox<String> Benef22;
    private javax.swing.JComboBox<String> Benef23;
    private javax.swing.JComboBox<String> Benef24;
    private javax.swing.JComboBox<String> Benef25;
    private javax.swing.JComboBox<String> Benef26;
    private javax.swing.JTextField Benef27;
    private javax.swing.JComboBox<String> Benef28;
    private javax.swing.JTextField Benef29;
    private javax.swing.JTextField Benef3;
    private javax.swing.JTextField Benef30;
    private javax.swing.JTextField Benef31;
    private javax.swing.JComboBox<String> Benef33;
    private javax.swing.JComboBox<String> Benef34;
    private javax.swing.JComboBox<String> Benef35;
    private javax.swing.JComboBox<String> Benef36;
    private javax.swing.JComboBox<String> Benef37;
    private javax.swing.JTextField Benef38;
    private javax.swing.JTextField Benef4;
    private javax.swing.JTextField Benef40;
    private javax.swing.JTextField Benef42;
    private javax.swing.JComboBox<String> Benef44;
    private javax.swing.JComboBox<String> Benef45;
    private javax.swing.JComboBox<String> Benef46;
    private javax.swing.JComboBox<String> Benef47;
    private javax.swing.JComboBox<String> Benef48;
    private javax.swing.JTextField Benef5;
    private javax.swing.JTextField Benef6;
    private javax.swing.JTextField Benef7;
    private javax.swing.JTextField Benef8;
    private javax.swing.JTextField Benef9;
    private javax.swing.JButton ContratarHogar;
    private javax.swing.JCheckBox RespCiv;
    private javax.swing.JCheckBox TercComp;
    private javax.swing.JComboBox<String> TipCobertura;
    private javax.swing.JCheckBox TrConFran;
    private javax.swing.JCheckBox TrSinFran;
    private javax.swing.JTextField anImp;
    private javax.swing.JCheckBox cocina;
    private javax.swing.JComboBox<String> comboFranquicia;
    private javax.swing.JComboBox<String> comboMarca;
    private javax.swing.JTextField cuilImp;
    private javax.swing.JComboBox<String> diasV;
    private javax.swing.JTextField domTxt;
    private javax.swing.JCheckBox games;
    private javax.swing.JCheckBox granizoCheck;
    private javax.swing.JCheckBox hel;
    private javax.swing.JCheckBox incendioC;
    private javax.swing.JCheckBox internacionV;
    private javax.swing.JCheckBox inundacionC;
    private javax.swing.JComboBox<String> item2V;
    private javax.swing.JComboBox<String> item3V;
    private javax.swing.JComboBox<String> item4V;
    private javax.swing.JComboBox<String> itemV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox lav;
    private javax.swing.JTextField mailImp;
    private javax.swing.JComboBox<String> modelImp;
    private javax.swing.JCheckBox muerteV;
    private javax.swing.JCheckBox muerteVA;
    private javax.swing.JCheckBox net;
    private javax.swing.JTextField nomImp;
    private javax.swing.JCheckBox paralisisV;
    private javax.swing.JCheckBox roboC;
    private javax.swing.JCheckBox tel;
    private javax.swing.JTextField telImp;
    // End of variables declaration//GEN-END:variables
}
